/*---------------------------------------------------------------------------------------------
 *  Agent Models - Data types for the Agent system
 *  Follows VS Code convention: pure data types, no dependencies on browser/electron
 *--------------------------------------------------------------------------------------------*/

export const enum MessageRole {
	System = 'system',
	User = 'user',
	Assistant = 'assistant',
	Tool = 'tool',
}

export const enum AgentMode {
	Agent = 'agent',
	Ask = 'ask',
	Plan = 'plan',
}

export const enum StepStatus {
	Pending = 'pending',
	Running = 'running',
	Done = 'done',
	Failed = 'failed',
}

export interface IToolCall {
	readonly id: string;
	readonly name: string;
	readonly arguments: Record<string, unknown>;
}

export interface IAgentMessage {
	readonly id: string;
	readonly role: MessageRole;
	readonly content: string;
	readonly toolCalls?: IToolCall[];
	readonly toolCallId?: string;
	readonly timestamp: number;
	readonly reasoningContent?: string;
	/** Token usage reported by the LLM provider for the call that produced this message. */
	readonly usage?: ILlmUsage;
}

export interface IToolResult {
	readonly toolCallId: string;
	readonly success: boolean;
	readonly output: string;
	readonly error?: string;
}

/** Token usage reported by an LLM API response (provider-normalized). */
export interface ILlmUsage {
	/** Input/prompt tokens (context tokens consumed by the request). */
	readonly promptTokens: number;
	/** Output/completion tokens generated by the model. */
	readonly completionTokens: number;
	/** Total tokens for the call (prompt + completion). */
	readonly totalTokens: number;
	/** Input tokens served from provider cache (cache hit / cache read), 0 when not reported. */
	readonly cachedTokens?: number;
	/** Input tokens written into the provider cache on this call (cache creation), 0 when not reported. */
	readonly cacheCreationTokens?: number;
}

export interface IToolSchema {
	readonly type: 'function';
	readonly function: {
		readonly name: string;
		readonly description: string;
		readonly parameters: Record<string, unknown>;
	};
}

export interface IAgentStep {
	readonly id: number;
	readonly description: string;
	status: StepStatus;
	toolName?: string;
	toolArgs?: Record<string, unknown>;
	result?: string;
}

export interface IAgentPlan {
	readonly task: string;
	readonly steps: IAgentStep[];
	currentStep: number;
}

export interface IAgentSession {
	readonly id: string;
	readonly name: string;
	readonly mode: AgentMode;
	readonly messages: IAgentMessage[];
	readonly systemPrompt?: string;
	readonly extraSystemPrompt?: string;
	readonly workingDirectory?: string;
	plan?: IAgentPlan;
	readonly createdAt: number;
	readonly updatedAt: number;
	readonly messageCount: number;
	readonly summary?: string;
}

export interface IAgentConfig {
	provider: 'openai' | 'anthropic' | 'ollama';
	model: string;
	apiKey: string;
	apiBase?: string;
	maxSteps: number;
	maxContextTokens: number;
	maxOutputTokens: number;
	temperature: number;
	/**
	 * Top-K sampling (only a subset of the highest-probability tokens is
	 * considered at each step). 0/undefined = not sent to the API (provider
	 * default). Used to pin deterministic sampling for benchmarks.
	 */
	topK?: number;
	stepTimeout: number;
	taskTimeout: number;
}

/**
 * Runtime model switch record (scenario routing, /profile, or the 保底 fallback).
 * Fired by AgentLoop so the CLI/IDE can tell the user which model is answering —
 * an invisible model swap makes a wrong/throttled answer impossible to diagnose.
 */
export interface IModelSwitchEvent {
	/** Model id that was active before the switch. */
	from: string;
	/** Model id that is active after the switch. */
	to: string;
	/**
	 * Why the switch happened:
	 *   - 'fallback-timeout'  : the primary/scenario model timed out → 保底模型
	 *   - 'primary-recovered' : the primary model is reachable again → switch back
	 *   - 'routing'           : scenario-based routing before a new task
	 *   - 'profile'           : the user switched profile via /profile
	 */
	reason: 'fallback-timeout' | 'primary-recovered' | 'routing' | 'profile';
	/** True when the switch moves TO the 保底 (fallback) model. */
	toFallback: boolean;
	/** Optional human-readable detail (e.g. the timeout error message). */
	detail?: string;
	/** Epoch ms when the switch happened (set when recorded in a task log). */
	at?: number;
}

/** Per-step tool execution record for task log tracing. */
export interface IToolExecutionRecord {
	readonly toolCallId: string;
	readonly toolName: string;
	readonly arguments: Record<string, unknown>;
	readonly result: string;
	readonly success: boolean;
	readonly error?: string;
	readonly durationMs: number;
	readonly timestamp: number;
}

/** Per-step LLM interaction record for task log tracing. */
export interface IStepRecord {
	readonly stepIndex: number;
	readonly llmRequest: {
		messageCount: number;
		estimatedTokens: number;
	};
	readonly llmResponse: {
		content: string;
		toolCalls?: IToolCall[];
		reasoningContent?: string;
	};
	/** Actual token usage reported by the LLM API for this step's completion call. */
	readonly llmUsage?: ILlmUsage;
	readonly toolExecutions: IToolExecutionRecord[];
	readonly durationMs: number;
	readonly timestamp: number;
}

/**
 * Something that went wrong (or nearly did) during a task, recorded in the task
 * log so self-evolution evidence is a first-class fact instead of prose that has
 * to be re-parsed from the transcript later.
 */
export interface IIssueSignal {
	readonly kind:
		| 'user-intervention'      // the user had to steer the agent mid-task (/btw)
		| 'step-limit'            // the task ran out of steps
		| 'reasoning-loop'         // the model repeated itself and produced no answer
		| 'context-overflow'       // history had to be compacted and the call retried
		| 'model-fallback'         // the primary model timed out and the 保底 model took over
		| 'verification-round'     // a self-verification round had to be injected
		| 'unknown-tool';          // the model called a tool that does not exist
	readonly detail?: string;
	readonly stepIndex?: number;
}

/** Complete execution log for a single task, persisted for troubleshooting. */
export interface IAgentTaskLog {
	readonly id: string;
	readonly task: string;
	readonly mode: AgentMode;
	readonly workingDirectory: string;
	readonly config: {
		provider: string;
		model: string;
	};
	readonly systemPrompt: string;
	readonly extraSystemPrompt?: string;
	/** Runtime model switches that happened during this task (routing / 保底 / recovery). */
	readonly modelSwitches?: IModelSwitchEvent[];
	/**
	 * Problems observed during the task (loop corrections, compactions, forced
	 * fallbacks, user interventions, unknown tools). Read by the self-evolution
	 * evidence scan so a defect can be traced back to the runs that hit it.
	 */
	readonly issueSignals?: IIssueSignal[];
	readonly steps: IStepRecord[];
	readonly totalSteps: number;
	readonly totalToolCalls: number;
	/** Aggregated token usage across all LLM calls in this task (sum of step llmUsage). */
	readonly tokenUsage?: ILlmUsage;
	readonly status: 'completed' | 'failed' | 'cancelled';
	readonly error?: string;
	readonly startedAt: number;
	readonly finishedAt: number;
	readonly durationMs: number;
}

export const DEFAULT_AGENT_CONFIG: IAgentConfig = {
	provider: 'openai',
	model: 'deepseek-v4-pro',
	apiKey: '',
	maxSteps: 999999,  // Effectively unlimited
	maxContextTokens: 200000,
	maxOutputTokens: 65536,
	temperature: 0,
	topK: 0,  // 0 = provider default (not sent); set >0 to pin top_k for reproducible benchmarks
	stepTimeout: 300000,  // 5 minutes - allow tools with custom timeouts to complete
	taskTimeout: 3600000,  // 1 hour
};

export function createMessage(
	role: MessageRole,
	content: string,
	extra?: Partial<IAgentMessage>
): IAgentMessage {
	return {
		id: generateId(),
		role,
		content,
		timestamp: Date.now(),
		...extra,
	};
}

export function createToolResultMessage(result: IToolResult): IAgentMessage {
	const content = result.output || result.error || '(no output)';
	return createMessage(MessageRole.Tool, content, {
		toolCallId: result.toolCallId,
	});
}

let _idCounter = 0;
export function generateId(): string {
	return `msg_${Date.now()}_${_idCounter++}`;
}
